import type {
  PipelineStats,
  CategoryBreakdown,
  CrawlJobStatus,
  ActivityEvent,
  Contact,
  OutreachRecord,
  PipelineStage,
  JobLogEntry,
} from "./types";

export const mockPipelineStats: PipelineStats = {
  rawResults: 3842,
  domains: 1621,
  cleanedDomains: 847,
  crawlJobs: 612,
  extractedContacts: 2304,
};

export const mockCategoryBreakdown: CategoryBreakdown[] = [
  {
    category: "college_art",
    rawResults: 1240,
    domains: 518,
    cleanedRelevant: 280,
    crawled: 210,
    contacts: 891,
  },
  {
    category: "college_chinese",
    rawResults: 820,
    domains: 312,
    cleanedRelevant: 198,
    crawled: 155,
    contacts: 621,
  },
  {
    category: "golf_clubs",
    rawResults: 1090,
    domains: 508,
    cleanedRelevant: 242,
    crawled: 180,
    contacts: 540,
  },
  {
    category: "hs_art",
    rawResults: 692,
    domains: 283,
    cleanedRelevant: 127,
    crawled: 67,
    contacts: 252,
  },
];

export const mockCrawlJobStatus: CrawlJobStatus = {
  pending: 48,
  completed: 612,
  failed: 23,
};

export const mockActivityFeed: ActivityEvent[] = [
  {
    id: "1",
    type: "extract",
    message: "Found 34 emails at University of Chicago Art Department",
    timestamp: "2026-05-12T14:32:00Z",
    category: "college_art",
  },
  {
    id: "2",
    type: "crawl",
    message: "Finished researching Pine Valley Golf & Country Club",
    timestamp: "2026-05-12T14:28:00Z",
    category: "golf_clubs",
  },
  {
    id: "3",
    type: "clean",
    message: "Reviewed 120 organizations — 67 added to pipeline",
    timestamp: "2026-05-12T14:15:00Z",
    category: "college_chinese",
  },
  {
    id: "4",
    type: "extract",
    message: "Found 18 emails at Stanford Chinese Language Program",
    timestamp: "2026-05-12T13:58:00Z",
    category: "college_chinese",
  },
  {
    id: "5",
    type: "collect",
    message: "Discovered 89 new high school art programs",
    timestamp: "2026-05-12T13:40:00Z",
    category: "hs_art",
  },
  {
    id: "6",
    type: "crawl",
    message: "Could not reach one organization — will retry",
    timestamp: "2026-05-12T13:22:00Z",
    category: "college_art",
  },
  {
    id: "7",
    type: "collect",
    message: "Discovered 145 new golf clubs",
    timestamp: "2026-05-12T12:55:00Z",
    category: "golf_clubs",
  },
  {
    id: "8",
    type: "outreach",
    message: "Email sent to James Chen at Stanford",
    timestamp: "2026-05-12T12:30:00Z",
    category: "college_chinese",
  },
];

export const mockContacts: Contact[] = [
  {
    id: "c1",
    domain: "art.uchicago.edu",
    category: "college_art",
    email: "sarah.klein@art.uchicago.edu",
    name: "Sarah Klein",
    title: "Department Chair",
    role_type: "decision_maker",
    is_targeted: true,
    confidence: 0.94,
    page_url: "https://art.uchicago.edu/people/faculty",
    extracted_at: "2026-05-12T14:32:00Z",
    org_name: "University of Chicago — Department of Art History",
    org_description: "Top-ranked art history program offering BA, MA, and PhD. Research focus on modern and contemporary art.",
    sales_notes: "Large department, likely budget for software. Chair has published on digital humanities — good angle.",
    contact_summary: "Sarah is department chair, active researcher, responds to peer outreach. LinkedIn present.",
  },
  {
    id: "c2",
    domain: "art.uchicago.edu",
    category: "college_art",
    email: "tom.wu@art.uchicago.edu",
    name: "Tom Wu",
    title: "Adjunct Professor",
    role_type: "faculty",
    is_targeted: false,
    confidence: 0.78,
    page_url: "https://art.uchicago.edu/people/faculty",
    extracted_at: "2026-05-12T14:32:00Z",
    org_name: "University of Chicago — Department of Art History",
    org_description: "Top-ranked art history program offering BA, MA, and PhD. Research focus on modern and contemporary art.",
    sales_notes: null,
    contact_summary: null,
  },
  {
    id: "c3",
    domain: "chinese.stanford.edu",
    category: "college_chinese",
    email: "james.chen@chinese.stanford.edu",
    name: "James Chen",
    title: "Program Director",
    role_type: "decision_maker",
    is_targeted: true,
    confidence: 0.91,
    page_url: "https://chinese.stanford.edu/people",
    extracted_at: "2026-05-12T13:58:00Z",
    org_name: "Stanford University — Chinese Language Program",
    org_description: "Comprehensive Chinese language and culture program serving 800+ students annually.",
    sales_notes: "Program is growing — added 2 new sections this year. Director controls curriculum budget.",
    contact_summary: "James runs the program day-to-day. Very accessible — hosts office hours publicly listed.",
  },
  {
    id: "c4",
    domain: "pinevalleygc.com",
    category: "golf_clubs",
    email: "director@pinevalleygc.com",
    name: "Robert Haines",
    title: "Club Director",
    role_type: "decision_maker",
    is_targeted: true,
    confidence: 0.88,
    page_url: "https://pinevalleygc.com/contact",
    extracted_at: "2026-05-12T14:28:00Z",
    org_name: "Pine Valley Golf & Country Club",
    org_description: "Private members-only club established 1922. 450 members, 18-hole championship course.",
    sales_notes: "High-end club with significant budget. Annual events calendar suggests active purchasing.",
    contact_summary: "Director handles vendor relationships. Email is listed on official contact page.",
  },
  {
    id: "c5",
    domain: "pinevalleygc.com",
    category: "golf_clubs",
    email: "events@pinevalleygc.com",
    name: null,
    title: "Events Coordinator",
    role_type: "coordinator",
    is_targeted: false,
    confidence: 0.65,
    page_url: "https://pinevalleygc.com/events",
    extracted_at: "2026-05-12T14:28:00Z",
    org_name: "Pine Valley Golf & Country Club",
    org_description: "Private members-only club established 1922. 450 members, 18-hole championship course.",
    sales_notes: null,
    contact_summary: null,
  },
  {
    id: "c6",
    domain: "westlakehs.edu",
    category: "hs_art",
    email: "mwilliams@westlakehs.edu",
    name: "Maria Williams",
    title: "Art Department Head",
    role_type: "decision_maker",
    is_targeted: true,
    confidence: 0.82,
    page_url: "https://westlakehs.edu/departments/art",
    extracted_at: "2026-05-11T16:10:00Z",
    org_name: "Westlake High School — Art Department",
    org_description: "Public high school with award-winning visual arts program, serving grades 9–12.",
    sales_notes: "Budget likely limited but department head has purchase authority for under $500.",
    contact_summary: "Maria has been dept head 4 years. Active on school social media promoting student work.",
  },
  {
    id: "c7",
    domain: "risd.edu",
    category: "college_art",
    email: "admissions@risd.edu",
    name: null,
    title: null,
    role_type: "generic",
    is_targeted: false,
    confidence: 0.41,
    page_url: "https://risd.edu/contact",
    extracted_at: "2026-05-11T12:00:00Z",
    org_name: "Rhode Island School of Design",
    org_description: "World-renowned art and design school. Over 2,700 students.",
    sales_notes: null,
    contact_summary: null,
  },
  {
    id: "c8",
    domain: "mandarin-uc.edu",
    category: "college_chinese",
    email: "info@mandarin-uc.edu",
    name: "Li Fang",
    title: "Language Center Director",
    role_type: "decision_maker",
    is_targeted: true,
    confidence: 0.87,
    page_url: "https://mandarin-uc.edu/about",
    extracted_at: "2026-05-10T09:45:00Z",
    org_name: "UC Language Center — Mandarin Program",
    org_description: "University language center specializing in Mandarin immersion for undergraduates.",
    sales_notes: "Small program but director is very engaged. Responded to a prior cold email within 24h.",
    contact_summary: "Li Fang manages operations and curriculum. Known for adopting new teaching tech.",
  },
];

export const mockOutreachRecords: OutreachRecord[] = [
  {
    id: "o1",
    contact: mockContacts[0],
    status: "replied",
    subject: "Streamline your department's contact research",
    sent_at: "2026-05-10T10:00:00Z",
    replied_at: "2026-05-11T08:30:00Z",
  },
  {
    id: "o2",
    contact: mockContacts[2],
    status: "sent",
    subject: "Quick question about Chinese program resources",
    sent_at: "2026-05-12T12:30:00Z",
    replied_at: null,
  },
  {
    id: "o3",
    contact: mockContacts[3],
    status: "sent",
    subject: "Connecting with Pine Valley",
    sent_at: "2026-05-11T15:00:00Z",
    replied_at: null,
  },
  {
    id: "o4",
    contact: mockContacts[5],
    status: "bounced",
    subject: "For Westlake Art Department",
    sent_at: "2026-05-09T09:00:00Z",
    replied_at: null,
  },
  {
    id: "o5",
    contact: mockContacts[7],
    status: "replied",
    subject: "Mandarin program tool question",
    sent_at: "2026-05-08T11:00:00Z",
    replied_at: "2026-05-09T14:20:00Z",
  },
];

export const mockPipelineStages: PipelineStage[] = [
  {
    id: "collect",
    name: "Discover",
    description: "Find new organizations matching your target categories",
    status: "success",
    lastRunAt: "2026-05-12T13:40:00Z",
    itemsProcessed: 847,
  },
  {
    id: "crawl",
    name: "Research",
    description: "Visit each organization's website and collect details",
    status: "running",
    lastRunAt: "2026-05-12T14:20:00Z",
    itemsProcessed: 612,
  },
  {
    id: "extract",
    name: "Find Contacts",
    description: "Identify emails and key people at each organization",
    status: "idle",
    lastRunAt: "2026-05-12T14:32:00Z",
    itemsProcessed: 2304,
  },
];

export const mockJobLog: JobLogEntry[] = [
  { id: "l1", stage: "Crawl", message: "Starting crawl for art.uchicago.edu", level: "info", timestamp: "2026-05-12T14:20:01Z" },
  { id: "l2", stage: "Crawl", message: "Crawl complete: art.uchicago.edu — 8 pages", level: "info", timestamp: "2026-05-12T14:21:45Z" },
  { id: "l3", stage: "Crawl", message: "Firecrawl rate limit hit — waiting 2s", level: "warn", timestamp: "2026-05-12T14:22:00Z" },
  { id: "l4", stage: "Crawl", message: "Starting crawl for artdept-fake.edu", level: "info", timestamp: "2026-05-12T14:22:10Z" },
  { id: "l5", stage: "Crawl", message: "Crawl failed: artdept-fake.edu — timeout after 30s", level: "error", timestamp: "2026-05-12T14:22:40Z" },
  { id: "l6", stage: "Crawl", message: "Starting crawl for pinevalleygc.com", level: "info", timestamp: "2026-05-12T14:23:00Z" },
  { id: "l7", stage: "Crawl", message: "Crawl complete: pinevalleygc.com — 12 pages", level: "info", timestamp: "2026-05-12T14:28:00Z" },
  { id: "l8", stage: "Extract", message: "Extracted 34 contacts from art.uchicago.edu", level: "info", timestamp: "2026-05-12T14:32:00Z" },
];
